@echo off
chcp 65001 >nul 2>&1
setlocal enabledelayedexpansion

echo.
echo  ╔══════════════════════════════════════════════════╗
echo  ║          🤖 Seeker.Bot — Installation            ║
echo  ╚══════════════════════════════════════════════════╝
echo.

REM ── Step 1: Check Python ──
echo  [1/6] Checking Python...
python --version >nul 2>&1
if errorlevel 1 (
    echo  ❌ Python not found! Please install Python 3.10+ from https://python.org
    echo     Make sure to check "Add Python to PATH" during installation.
    pause
    exit /b 1
)
for /f "tokens=2 delims= " %%v in ('python --version 2^>^&1') do set PYVER=%%v
echo  ✅ Python %PYVER% detected
echo.

REM ── Step 2: Create virtual environment ──
echo  [2/6] Creating virtual environment...
if not exist ".venv" (
    python -m venv .venv
    echo  ✅ Virtual environment created
) else (
    echo  ✅ Virtual environment already exists
)
call .venv\Scripts\activate.bat
echo.

REM ── Step 3: Install dependencies ──
echo  [3/6] Installing dependencies...
pip install -r requirements.txt -q
pip install pyyaml -q
echo  ✅ Dependencies installed
echo.

REM ── Step 4: Assistant Name ──
echo  ═══════════════════════════════════════════════════
echo   🎭 Personalize your assistant!
echo  ═══════════════════════════════════════════════════
echo.
echo   Give your AI assistant a name.
echo   This is how it will introduce itself in conversations.
echo   (Press ENTER for default: Seeker)
echo.
set /p ASSISTANT_NAME="   Your assistant's name: "
if "!ASSISTANT_NAME!"=="" set ASSISTANT_NAME=Seeker
echo.
echo  ✅ Your assistant will be called: %ASSISTANT_NAME%
echo.

REM ── Step 5: Operation Mode ──
echo  ═══════════════════════════════════════════════════
echo   ⚡ Choose your operation mode
echo  ═══════════════════════════════════════════════════
echo.
echo   [1] ☁️  Cloud Mode (requires API keys — recommended)
echo       Uses online AI models. Free tiers available.
echo.
echo   [2] 🏠 Local Mode (requires Ollama + GPU)
echo       Runs 100%% offline. No API keys needed.
echo       Requires a GPU with 8GB+ VRAM.
echo.
set /p MODE_CHOICE="   Your choice [1/2]: "
if "!MODE_CHOICE!"=="2" (
    set SEEKER_MODE=local
    echo.
    echo  Detecting GPU...
    for /f "tokens=*" %%g in ('nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2^>nul') do set VRAM_MB=%%g
    if defined VRAM_MB (
        set /a VRAM_GB=!VRAM_MB! / 1024
        echo  ✅ GPU detected: !VRAM_GB! GB VRAM
    ) else (
        echo  ⚠️  Could not detect GPU. Defaulting to 8GB profile.
        set VRAM_GB=8
    )
    set LOCAL_VRAM_GB=!VRAM_GB!
) else (
    set SEEKER_MODE=cloud
    set LOCAL_VRAM_GB=8
)
echo.

REM ── Step 6: Skill Selection ──
echo  ═══════════════════════════════════════════════════
echo   🛠️  Choose your skills profile
echo  ═══════════════════════════════════════════════════
echo.
echo   [1] 🟢 Core Only (3 skills — minimum functional)
echo       Health Monitor, Self-Improvement, Daily Briefing
echo.
echo   [2] 🟡 Core + Recommended (9 skills — recommended)
echo       + Knowledge Vault, Scheduler, News, Bug Analyzer...
echo.
echo   [3] 🔵 All Skills (17 skills — full power)
echo       + Sales, Events, Email, Desktop Watch, Remote Exec...
echo       (Some require extra configuration)
echo.
set /p SKILL_CHOICE="   Your choice [1/2/3]: "

REM Generate config/skills.yaml based on choice
if not exist "config" mkdir config

if "!SKILL_CHOICE!"=="1" (
    set REC_ENABLED=false
    set SPEC_ENABLED=false
) else if "!SKILL_CHOICE!"=="3" (
    set REC_ENABLED=true
    set SPEC_ENABLED=true
) else (
    set REC_ENABLED=true
    set SPEC_ENABLED=false
)

(
echo # Seeker.Bot — Skills Configuration
echo # Generated by install.bat
echo.
echo core:
echo   health_monitor: true
echo   self_improvement: true
echo   briefing: true
echo.
echo recommended:
echo   knowledge_vault: !REC_ENABLED!
echo   scheduler_conversacional: !REC_ENABLED!
echo   sense_news: !REC_ENABLED!
echo   sherlock_news: !REC_ENABLED!
echo   bug_analyzer: !REC_ENABLED!
echo   skill_creator: !REC_ENABLED!
echo.
echo specialist:
echo   seeker_sales: !SPEC_ENABLED!
echo   event_map_scout: !SPEC_ENABLED!
echo   seeker_sales_week: !SPEC_ENABLED!
echo   email_monitor: !SPEC_ENABLED!
echo   desktop_watch: !SPEC_ENABLED!
echo   remote_executor: !SPEC_ENABLED!
echo   os_control: !SPEC_ENABLED!
echo   git_automation: !SPEC_ENABLED!
) > config\skills.yaml

echo  ✅ Skills configured!
echo.

REM ── Generate .env ──
echo  ═══════════════════════════════════════════════════
echo   🔑 Configuring environment...
echo  ═══════════════════════════════════════════════════

if not exist ".env" (
    copy .env.example .env >nul

    REM Replace defaults with user choices
    powershell -Command "(Get-Content .env) -replace 'ASSISTANT_NAME=Seeker', 'ASSISTANT_NAME=!ASSISTANT_NAME!' | Set-Content .env"
    powershell -Command "(Get-Content .env) -replace 'SEEKER_MODE=cloud', 'SEEKER_MODE=!SEEKER_MODE!' | Set-Content .env"
    powershell -Command "(Get-Content .env) -replace 'LOCAL_VRAM_GB=8', 'LOCAL_VRAM_GB=!LOCAL_VRAM_GB!' | Set-Content .env"

    echo  ✅ .env created from template
) else (
    echo  ⚠️  .env already exists — skipping (won't overwrite your keys)
)
echo.

REM ── Ollama Setup (if local mode) ──
if "!SEEKER_MODE!"=="local" (
    echo  ═══════════════════════════════════════════════════
    echo   🏠 Setting up Local Mode...
    echo  ═══════════════════════════════════════════════════
    echo.
    ollama --version >nul 2>&1
    if errorlevel 1 (
        echo  ❌ Ollama not found!
        echo     Please install from: https://ollama.com/download
        echo     Then run this installer again.
        pause
        exit /b 1
    )
    echo  ✅ Ollama detected
    echo  📥 Pulling required models (this may take a while)...
    echo.
    ollama pull qwen3.5:4b
    ollama pull nomic-embed-text
    echo.
    echo  ✅ Local models ready!
    echo.
)

REM ── Final Instructions ──
echo.
echo  ╔══════════════════════════════════════════════════╗
echo  ║          ✅ Installation Complete!               ║
echo  ╚══════════════════════════════════════════════════╝
echo.
echo  📝 Next steps:
echo.
if "!SEEKER_MODE!"=="cloud" (
    echo  1. Open .env in your text editor and fill in your API keys:
    echo     - TELEGRAM_BOT_TOKEN  (required — get from @BotFather)
    echo     - TELEGRAM_ALLOWED_USERS  (required — get from @userinfobot)
    echo     - GEMINI_API_KEY  (required — https://aistudio.google.com/apikey)
    echo.
    echo  2. Run: start_watchdog.bat
) else (
    echo  1. Open .env and fill in:
    echo     - TELEGRAM_BOT_TOKEN  (required — get from @BotFather)
    echo     - TELEGRAM_ALLOWED_USERS  (required — get from @userinfobot)
    echo.
    echo  2. Make sure Ollama is running: ollama serve
    echo  3. Run: start_watchdog.bat
)
echo.
echo  🎉 Your assistant "%ASSISTANT_NAME%" is ready!
echo.

REM Open .env for editing
set /p OPEN_ENV="   Open .env now for editing? [Y/N]: "
if /i "!OPEN_ENV!"=="Y" notepad .env

endlocal
pause
