#!/usr/bin/env python3
"""
Seeker.Bot Interactive Setup
Instalador bilíngue (Português/English) com configuração automática.
"""

import os
import sys
import subprocess
import json
from pathlib import Path


def clear_screen():
    """Limpa a tela do terminal."""
    os.system("cls" if os.name == "nt" else "clear")


def get_language():
    """Pergunta ao usuário qual idioma usar."""
    clear_screen()
    print("=" * 60)
    print("Seeker.Bot Setup")
    print("=" * 60)
    print()
    print("Choose language / Escolha o idioma:")
    print()
    print("[1] Português (Brasil)")
    print("[2] English")
    print()
    choice = input("> ").strip()
    return "pt_BR" if choice == "1" else "en_US"


def show_welcome(lang):
    """Exibe mensagem de boas-vindas."""
    clear_screen()
    if lang == "pt_BR":
        print("=" * 60)
        print("🤖 Bem-vindo ao Seeker.Bot!")
        print("=" * 60)
        print()
        print("Seeker.Bot é um agente autônomo de pesquisa com:")
        print("  ✓ Raciocínio estruturado em 3 camadas")
        print("  ✓ Memória semântica persistente")
        print("  ✓ Multi-provider LLM com fallback automático")
        print("  ✓ Skills dinâmicas criáveis via chat")
        print()
        print("Este instalador irá:")
        print("  1. Instalar dependências (pip)")
        print("  2. Configurar variáveis de ambiente (.env)")
        print("  3. Criar banco de dados inicial")
        print("  4. Testar conectividade com providers")
        print()
    else:
        print("=" * 60)
        print("🤖 Welcome to Seeker.Bot!")
        print("=" * 60)
        print()
        print("Seeker.Bot is an autonomous research agent with:")
        print("  ✓ Structured 3-layer reasoning")
        print("  ✓ Persistent semantic memory")
        print("  ✓ Multi-provider LLM with automatic fallback")
        print("  ✓ Dynamic skills creatable via chat")
        print()
        print("This installer will:")
        print("  1. Install dependencies (pip)")
        print("  2. Configure environment variables (.env)")
        print("  3. Create initial database")
        print("  4. Test provider connectivity")
        print()

    input("Press Enter to continue / Pressione Enter para continuar...")


def get_api_keys(lang):
    """Coleta as API keys do usuário."""
    clear_screen()
    keys = {}

    if lang == "pt_BR":
        print("=" * 60)
        print("🔑 Configurar API Keys")
        print("=" * 60)
        print()
        print("Cole suas API keys. Use Enter para pular (padrões serão usados).")
        print()
    else:
        print("=" * 60)
        print("🔑 Configure API Keys")
        print("=" * 60)
        print()
        print("Paste your API keys. Press Enter to skip (defaults will be used).")
        print()

    prompts = {
        "pt_BR": {
            "groq": "Groq API Key (https://console.groq.com): ",
            "gemini": "Google Gemini API Key (https://makersuite.google.com): ",
            "deepseek": "DeepSeek API Key (https://platform.deepseek.com): ",
            "tavily": "Tavily Search API Key (https://tavily.com): ",
            "telegram": "Telegram Bot Token (BotFather): ",
        },
        "en_US": {
            "groq": "Groq API Key (https://console.groq.com): ",
            "gemini": "Google Gemini API Key (https://makersuite.google.com): ",
            "deepseek": "DeepSeek API Key (https://platform.deepseek.com): ",
            "tavily": "Tavily Search API Key (https://tavily.com): ",
            "telegram": "Telegram Bot Token (BotFather): ",
        }
    }

    for key_name, prompt_text in prompts[lang].items():
        value = input(prompt_text).strip()
        if value:
            keys[key_name] = value

    return keys


def create_env_file(lang, keys):
    """Cria arquivo .env com configurações."""
    env_path = Path(".env")

    if env_path.exists():
        return  # Já existe, não sobrescrever

    env_content = f"""# Seeker.Bot Configuration
# Auto-generated by setup.py

# Idioma / Language
LANGUAGE={lang}

# API Keys
GROQ_API_KEY={keys.get('groq', '')}
GEMINI_API_KEY={keys.get('gemini', '')}
DEEPSEEK_API_KEY={keys.get('deepseek', '')}
TAVILY_API_KEY={keys.get('tavily', '')}

# Telegram
TELEGRAM_BOT_TOKEN={keys.get('telegram', '')}
TELEGRAM_ADMIN_USER_ID=1234567890

# Database
DATABASE_PATH=data/seeker_memory.db

# Logging
LOG_LEVEL=INFO

# Ollama (para fallback local)
OLLAMA_BASE_URL=http://localhost:11434
"""

    with open(env_path, "w") as f:
        f.write(env_content)


def install_dependencies(lang):
    """Instala dependências via pip."""
    clear_screen()

    if lang == "pt_BR":
        print("=" * 60)
        print("📦 Instalando dependências...")
        print("=" * 60)
        print()
    else:
        print("=" * 60)
        print("📦 Installing dependencies...")
        print("=" * 60)
        print()

    try:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-q", "-e", "."],
            cwd=Path(__file__).parent
        )

        if lang == "pt_BR":
            print("✅ Dependências instaladas com sucesso!")
        else:
            print("✅ Dependencies installed successfully!")

        input("Press Enter to continue / Pressione Enter para continuar...")

    except subprocess.CalledProcessError as e:
        if lang == "pt_BR":
            print(f"❌ Erro ao instalar dependências: {e}")
        else:
            print(f"❌ Error installing dependencies: {e}")
        sys.exit(1)


def test_providers(lang, keys):
    """Testa conectividade com os providers."""
    clear_screen()

    if lang == "pt_BR":
        print("=" * 60)
        print("🧪 Testando providers...")
        print("=" * 60)
        print()
    else:
        print("=" * 60)
        print("🧪 Testing providers...")
        print("=" * 60)
        print()

    providers_ok = 0
    providers_total = 3

    # Test Groq
    if keys.get("groq"):
        try:
            import httpx
            client = httpx.Client()
            resp = client.get("https://api.groq.com/api/health")
            if resp.status_code == 200:
                if lang == "pt_BR":
                    print("✅ Groq: OK")
                else:
                    print("✅ Groq: OK")
                providers_ok += 1
        except:
            if lang == "pt_BR":
                print("❌ Groq: Falha na conexão")
            else:
                print("❌ Groq: Connection failed")
    else:
        if lang == "pt_BR":
            print("⏭  Groq: Não configurado")
        else:
            print("⏭  Groq: Not configured")

    # Test Gemini
    if keys.get("gemini"):
        try:
            import httpx
            client = httpx.Client()
            resp = client.post(
                "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent",
                headers={"x-goog-api-key": keys["gemini"]},
                json={"contents": [{"parts": [{"text": "test"}]}]}
            )
            if resp.status_code in [200, 400]:  # 400 OK se key é válida mas request é inválido
                if lang == "pt_BR":
                    print("✅ Gemini: OK")
                else:
                    print("✅ Gemini: OK")
                providers_ok += 1
        except:
            if lang == "pt_BR":
                print("❌ Gemini: Falha na conexão")
            else:
                print("❌ Gemini: Connection failed")
    else:
        if lang == "pt_BR":
            print("⏭  Gemini: Não configurado")
        else:
            print("⏭  Gemini: Not configured")

    # Test Ollama (local)
    try:
        import httpx
        client = httpx.Client()
        resp = client.get("http://localhost:11434/api/tags")
        if resp.status_code == 200:
            if lang == "pt_BR":
                print("✅ Ollama (local): OK")
            else:
                print("✅ Ollama (local): OK")
            providers_ok += 1
    except:
        if lang == "pt_BR":
            print("⚠️  Ollama (local): Não disponível (opcional)")
        else:
            print("⚠️  Ollama (local): Not available (optional)")

    print()
    if lang == "pt_BR":
        print(f"Resultado: {providers_ok}/{providers_total} providers ativos")
        print()
        if providers_ok == 0:
            print("⚠️  Nenhum provider configurado. Configure API keys para usar o Bot.")
    else:
        print(f"Result: {providers_ok}/{providers_total} providers active")
        print()
        if providers_ok == 0:
            print("⚠️  No providers configured. Configure API keys to use the Bot.")

    input("Press Enter to continue / Pressione Enter para continuar...")


def show_summary(lang, keys):
    """Exibe resumo da configuração."""
    clear_screen()

    if lang == "pt_BR":
        print("=" * 60)
        print("✅ Setup Completo!")
        print("=" * 60)
        print()
        print("Próximos passos:")
        print("  1. Inicie o bot: python -m src")
        print("  2. Envie /start no Telegram")
        print("  3. Configure seus interesses (/configure_news)")
        print()
        print("Documentação: https://github.com/4pixeltech/Seeker.Bot")
        print()
    else:
        print("=" * 60)
        print("✅ Setup Complete!")
        print("=" * 60)
        print()
        print("Next steps:")
        print("  1. Start the bot: python -m src")
        print("  2. Send /start on Telegram")
        print("  3. Configure your interests (/configure_news)")
        print()
        print("Documentation: https://github.com/4pixeltech/Seeker.Bot")
        print()


def main():
    """Função principal."""
    lang = get_language()
    show_welcome(lang)

    keys = get_api_keys(lang)
    create_env_file(lang, keys)

    install_dependencies(lang)
    test_providers(lang, keys)
    show_summary(lang, keys)

    if lang == "pt_BR":
        print("Obrigado por usar Seeker.Bot! 🚀")
    else:
        print("Thank you for using Seeker.Bot! 🚀")


if __name__ == "__main__":
    main()
