"""
Core datastructures for Remote Executor.

ExecutionPlan:
    Multi-step action plan with dependencies, rollback, and cost estimation.
    Generated by ActionOrchestrator (LLM planning).

ActionStep:
    Individual action within an execution plan.
    Types: bash, file_ops, api, remote_trigger.
    Risk levels: L0_MANUAL (dangerous), L1_LOGGED (medium), L2_SILENT (safe).

ExecutionResult:
    Result of executing a single action.
    Contains: status, output, cost, duration, before/after snapshots, rollback info.
"""

import json
from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Any, Callable, Dict, List, Optional
from enum import Enum


class ActionType(str, Enum):
    """Action type for execution."""
    BASH = "bash"
    FILE_OPS = "file_ops"
    API = "api"
    REMOTE_TRIGGER = "remote_trigger"


class AutonomyTier(str, Enum):
    """Action approval/execution tier."""
    L0_MANUAL = "L0_MANUAL"        # Dangerous: requires user approval
    L1_LOGGED = "L1_LOGGED"        # Medium: auto-execute + log + AFK window check
    L2_SILENT = "L2_SILENT"        # Safe: auto-execute anytime (24h)


class ActionStatus(str, Enum):
    """Status of action execution."""
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    ROLLED_BACK = "rolled_back"
    CANCELLED = "cancelled"
    APPROVAL_PENDING = "approval_pending"


@dataclass
class SafetyGate:
    """Single safety gate evaluation for an action."""
    rule_id: str                    # e.g., "bash_whitelist_rm"
    rule_name: str                  # e.g., "Bash dangerous command blacklist"
    passed: bool                    # True if rule passed
    reason: str = ""                # Explanation if failed
    recommended_tier: AutonomyTier = AutonomyTier.L0_MANUAL  # Tier if rule applies


@dataclass
class ActionStep:
    """Single step within an execution plan."""
    id: str                             # Unique ID within plan (e.g., "step_1")
    type: ActionType                    # bash, file_ops, api, remote_trigger
    description: str                    # Human-readable description
    command: str | Dict[str, Any]      # Command/payload (bash string or dict for others)
    timeout_seconds: int = 30           # Timeout for this step
    approval_tier: AutonomyTier = AutonomyTier.L2_SILENT  # L0/L1/L2
    estimated_cost_usd: float = 0.0    # LLM/API cost for this step
    depends_on: List[str] = field(default_factory=list)  # Step IDs this depends on
    rollback_instruction: Optional[str] = None  # How to rollback if fails
    retry_count: int = 0               # Current retry count
    max_retries: int = 0               # Max retries allowed


@dataclass
class ExecutionResult:
    """Result of executing a single action step."""
    step_id: str                        # Which step was executed
    status: ActionStatus                # success, failed, etc.
    output: str = ""                    # stdout/result
    error: str = ""                     # stderr/exception message
    cost_usd: float = 0.0              # Actual cost (may differ from estimate)
    duration_ms: int = 0               # Execution time in milliseconds

    # Snapshots for audit trail (important for write operations)
    before_snapshot: Dict[str, Any] = field(default_factory=dict)  # State before
    after_snapshot: Dict[str, Any] = field(default_factory=dict)   # State after

    # Metadata
    executed_at: datetime = field(default_factory=datetime.utcnow)
    executed_by: str = "remote_executor"  # Which goal/module executed this


@dataclass
class ExecutionPlan:
    """Multi-step execution plan generated by ActionOrchestrator."""
    plan_id: str                        # Unique plan ID
    intention: str                      # Original user intention
    steps: List[ActionStep] = field(default_factory=list)  # Ordered list of steps
    dependencies: Dict[str, List[str]] = field(default_factory=dict)  # step_id → [prereq IDs]
    estimated_total_cost_usd: float = 0.0  # Total estimated cost
    safety_gates: List[SafetyGate] = field(default_factory=list)  # All gate evaluations
    safety_notes: str = ""              # Summary of safety considerations
    max_steps: int = 10                 # Max allowed steps (limit escalation)
    max_timeout_seconds: int = 60       # Max total timeout
    max_cost_usd: float = 0.20          # Max cost cap

    # State tracking
    created_at: datetime = field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = None  # When plan expires (e.g., 5 min from creation)
    status: str = "created"             # created, executing, completed, failed, cancelled


@dataclass
class ExecutionContext:
    """Context for execution (user, goals, budget, etc)."""
    plan_id: str
    triggered_by_user: str              # User ID or "system"
    triggered_by_intent: str            # Original user input
    goal_name: str = "remote_executor"  # Which goal is executing
    budget_remaining_usd: float = 0.20  # Remaining budget for this execution
    afk_time_seconds: int = 0           # How long user has been AFK
    afk_window_l1_hours: int = 12       # AFK window threshold for L1_LOGGED

    # Metadata
    created_at: datetime = field(default_factory=datetime.utcnow)


class ExecutionSnapshot:
    """Represents state snapshot for audit trail."""

    @staticmethod
    def capture_file_state(filepath: str) -> Dict[str, Any]:
        """Capture file state before/after operation."""
        import os
        from pathlib import Path

        if not os.path.exists(filepath):
            return {"exists": False, "path": filepath}

        path = Path(filepath)
        return {
            "exists": True,
            "path": str(path.absolute()),
            "is_file": path.is_file(),
            "is_dir": path.is_dir(),
            "size_bytes": path.stat().st_size if path.is_file() else None,
            "modified_at": datetime.fromtimestamp(path.stat().st_mtime).isoformat(),
            "permissions": oct(path.stat().st_mode),
        }

    @staticmethod
    def capture_dir_state(dirpath: str) -> Dict[str, Any]:
        """Capture directory state before/after operation."""
        import os
        from pathlib import Path

        if not os.path.exists(dirpath):
            return {"exists": False, "path": dirpath}

        path = Path(dirpath)
        files = list(path.glob("**/*"))
        return {
            "exists": True,
            "path": str(path.absolute()),
            "file_count": len([f for f in files if f.is_file()]),
            "dir_count": len([f for f in files if f.is_dir()]),
            "total_size_bytes": sum(f.stat().st_size for f in files if f.is_file()),
            "modified_at": datetime.fromtimestamp(path.stat().st_mtime).isoformat(),
        }

    @staticmethod
    def capture_git_state(repo_path: str = ".") -> Dict[str, Any]:
        """Capture git repository state."""
        import subprocess

        try:
            status = subprocess.run(
                ["git", "status", "--porcelain"],
                cwd=repo_path,
                capture_output=True,
                text=True,
                timeout=5,
                check=True
            )

            log = subprocess.run(
                ["git", "log", "--oneline", "-5"],
                cwd=repo_path,
                capture_output=True,
                text=True,
                timeout=5,
                check=True
            )

            return {
                "status": status.stdout.strip(),
                "recent_commits": log.stdout.strip(),
                "captured_at": datetime.utcnow().isoformat()
            }
        except Exception as e:
            return {"error": str(e)}


def execution_plan_to_json(plan: ExecutionPlan) -> str:
    """Serialize ExecutionPlan to JSON."""
    return json.dumps(asdict(plan), default=str, indent=2)


def execution_result_to_json(result: ExecutionResult) -> str:
    """Serialize ExecutionResult to JSON."""
    return json.dumps(asdict(result), default=str, indent=2)
